apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cine-sangeet-ingress
  namespace: cine-sangeet
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: cine-sangeet.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cine-sangeet-service
                port:
                  number: 80