apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cine-sangeet
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cine-sangeet
  endpoints:
  - port: http
    path: /metrics
    interval: 30s